//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "dishes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub kermesse_id: i32,
    pub name: String,
    pub description: String,
    pub price: Decimal,
    pub quantity_available: i32,
    pub image_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kermesses::Entity",
        from = "Column::KermesseId",
        to = "super::kermesses::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Kermesses,
    #[sea_orm(has_many = "super::sale_items::Entity")]
    SaleItems,
}

impl Related<super::kermesses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Kermesses.def()
    }
}

impl Related<super::sale_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
