//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ingredients")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub kermesse_id: i32,
    pub name: String,
    pub quantity_needed: Decimal,
    pub unit: String,
    pub is_donated: bool,
    pub donated_by_user_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kermesses::Entity",
        from = "Column::KermesseId",
        to = "super::kermesses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Kermesses,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::DonatedByUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::kermesses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Kermesses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
