//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod collaborators;
pub mod dishes;
pub mod ingredient_donations;
pub mod ingredients;
pub mod kermesses;
pub mod sale_items;
pub mod sales;
pub mod users;
