//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::collaborators::Entity as Collaborators;
pub use super::dishes::Entity as Dishes;
pub use super::ingredients::Entity as Ingredients;
pub use super::kermesses::Entity as Kermesses;
pub use super::sale_items::Entity as SaleItems;
pub use super::sales::Entity as Sales;
pub use super::users::Entity as Users;
