//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sales")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub kermesse_id: i32,
    pub seller_id: i32,
    pub customer_name: String,
    pub total_amount: Decimal,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub delivery_method: String,
    pub delivery_address: Option<String>,
    pub contact_phone: Option<String>,
    pub buyer_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kermesses::Entity",
        from = "Column::KermesseId",
        to = "super::kermesses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Kermesses,
    #[sea_orm(has_many = "super::sale_items::Entity")]
    SaleItems,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::BuyerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::SellerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users1,
}

impl Related<super::kermesses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Kermesses.def()
    }
}

impl Related<super::sale_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
