//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sale_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sale_id: i32,
    pub dish_id: i32,
    pub quantity: i32,
    pub subtotal: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dishes::Entity",
        from = "Column::DishId",
        to = "super::dishes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dishes,
    #[sea_orm(
        belongs_to = "super::sales::Entity",
        from = "Column::SaleId",
        to = "super::sales::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Sales,
}

impl Related<super::dishes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dishes.def()
    }
}

impl Related<super::sales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sales.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
